### ISSUE TITLE
Retry w/ exponential backoff nil pointer dereference since 3.2.1

### ISSUE THREAD

**Issue by RoarkeRandall** [cenkalti/backoff#88] opened 2020-01-13 21:45 UTC
usage:

```
	if err := backoff.Retry(doRequest, backoff.NewExponentialBackOff()); err != nil {
		return nil, err
	}
```

```
panic: runtime error: invalid memory address or nil pointer dereference [recovered]
	panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x28 pc=0x15b6716]

goroutine 35 [running]:
testing.tRunner.func1(0xc0002cc100)
	/usr/local/Cellar/go/1.12.7/libexec/src/testing/testing.go:830 +0x392
panic(0x1651d20, 0x1d5fe50)
	/usr/local/Cellar/go/1.12.7/libexec/src/runtime/panic.go:522 +0x1b5
time.(*Timer).Stop(...)
	/usr/local/Cellar/go/1.12.7/libexec/src/time/sleep.go:74
redacted/Concierge/privacy/vendor/github.com/cenkalti/backoff.(*defaultTimer).Stop(0xc0002ac010)
	/Users/roarker/godev/src/redacted/Concierge/privacy/vendor/github.com/cenkalti/backoff/timer.go:32 +0x26
redacted/Concierge/privacy/vendor/github.com/cenkalti/backoff.RetryNotifyWithTimer.func1(0x18e5440, 0xc0002ac010)
	/Users/roarker/godev/src/redacted/Concierge/privacy/vendor/github.com/cenkalti/backoff/retry.go:45 +0x31
redacted/Concierge/privacy/vendor/github.com/cenkalti/backoff.RetryNotifyWithTimer(0xc0002b4770, 0x18e0680, 0xc0002b2180, 0x0, 0x18e5440, 0xc0002ac010, 0x0, 0x0)
	/Users/roarker/godev/src/redacted/Concierge/privacy/vendor/github.com/cenkalti/backoff/retry.go:53 +0x31c
redacted/Concierge/privacy/vendor/github.com/cenkalti/backoff.RetryNotify(...)
	/Users/roarker/godev/src/redacted/Concierge/privacy/vendor/github.com/cenkalti/backoff/retry.go:31
redacted/Concierge/privacy/vendor/github.com/cenkalti/backoff.Retry(...)
	/Users/roarker/godev/src/redacted/Concierge/privacy/vendor/github.com/cenkalti/backoff/retry.go:25
```

**Comment by cenkalti** [comment] 2020-01-14 06:21
The problem is fixed in v4. Can you try upgrading to v4?

**Closed as completed** 2020-01-14 06:24 UTC
